#!/bin/sh
#
#  $Id: init_d_samba,v 1.1 2002/02/12 21:04:55 zigg Exp $
#
#  Start/stop script for Samba
#

case "$1" in
'start')
        ps -ef | awk '/usr.sbin.smbd/{print "kill",$2}' | sh
        ps -ef | awk '/usr.sbin.nmbd/{print "kill",$2}' | sh
        if [ -f /usr/sbin/nmbd ] ; then
                /usr/sbin/nmbd -D
                /usr/sbin/smbd -D
        fi
        ;;
'stop')
        ps -ef | awk '/usr.sbin.smbd/{print "kill",$2}' | sh
        ps -ef | awk '/usr.sbin.nmbd/{print "kill",$2}' | sh
        ;;
*)
        echo 'Usage: /etc/init.d/samba { start | stop }'
        exit 1
        ;;
esac

