# $Id: Makefile,v 1.2 2002/08/12 17:43:54 zigg Exp $

include ../GLOBAL/global.mk

PACKAGE_NAME =		gtar
PACKAGE_VERSION =	1.13

PACKAGE_SOURCE_NAME =	tar-${PACKAGE_VERSION}

PACKAGE_DESCRIPTION =	GNU tar
PACKAGE_CATEGORY =	utility

CONFIGURE_ARGS +=	--program-prefix=g --disable-nls
FAKE_DEST_VAR =

