# $Id: Makefile,v 1.4 2002/10/24 01:28:59 zigg Exp $

include ../GLOBAL/global.mk

PACKAGE_NAME =		cvs
PACKAGE_VERSION =	1.11.2

PACKAGE_DESCRIPTION =	Concurrent Versions System
PACKAGE_CATEGORY =	utility

CONFIGURE_ARGS +=	--without-gssapi
FAKE_DEST_VAR =

