# $Id: Makefile,v 1.2 2002/08/12 17:43:54 zigg Exp $

include ../GLOBAL/global.mk

PACKAGE_NAME =		fluxbox
PACKAGE_VERSION =	0.1.9

PACKAGE_SOURCE_NAME =	fluxbox-${PACKAGE_VERSION}

PACKAGE_DESCRIPTION =	Fluxbox Window Manager
PACKAGE_CATEGORY =	application

CONFIGURE_ARGS +=	--enable-ordered-pseudo
FAKE_DEST_VAR =

