# $Id: Makefile,v 1.2 2002/08/12 17:43:54 zigg Exp $

include ../GLOBAL/global.mk

PACKAGE_NAME =		bbkeys
PACKAGE_VERSION =	0.8.4

PACKAGE_DESCRIPTION =	Blackbox keygrabber
PACKAGE_CATEGORY =	utility

FAKE_DEST_VAR =

