# $Id: Makefile,v 1.3 2002/08/12 17:43:54 zigg Exp $

include ../GLOBAL/global.mk

PACKAGE_NAME =		mktemp
PACKAGE_VERSION =	1.4

PACKAGE_DESCRIPTION =	mktemp
PACKAGE_CATEGORY =	utility

DIST_FILES =		${PACKAGE_NAME}-${PACKAGE_VERSION}.tar.gz

