# $Id: Makefile,v 1.2 2002/08/12 17:43:54 zigg Exp $

include ../GLOBAL/global.mk

PACKAGE_NAME =		gnupg
PACKAGE_VERSION =	1.0.7

PACKAGE_DESCRIPTION =	GNU Privacy Guard
PACKAGE_CATEGORY =	application

FAKE_DEST_VAR =

