# $Id: Makefile,v 1.2 2002/08/12 17:43:54 zigg Exp $

include ../GLOBAL/global.mk

PACKAGE_NAME =		mutt
PACKAGE_VERSION =	1.2.5.1

PACKAGE_DESCRIPTION =	mutt
PACKAGE_CATEGORY =	utility

CONFIGURE_ARGS +=	--includedir=/nonexistent --enable-pop --enable-imap \
			--with-docdir=${INSTALL_PREFIX}/share/doc/mutt
FAKE_DEST_VAR =

