# $Id: Makefile,v 1.1 2002/08/12 17:37:25 zigg Exp $

include ../GLOBAL/global.mk

PACKAGE_NAME =		rxvt
PACKAGE_VERSION =	2.7.8

PACKAGE_DESCRIPTION =	Rxvt
PACKAGE_CATEGORY =	application

CONFIGURE_ARGS +=	--enable-keepscrolling \
			--enable-menubar \
			--enable-rxvt-scroll \
			--enable-shared \
			--enable-smart-resize \
			--enable-transparency \
			--enable-xpm-background
FAKE_DEST_VAR =

