# $Id: Makefile,v 1.4 2002/08/12 17:43:54 zigg Exp $

include ../GLOBAL/global.mk

PACKAGE_NAME =		blackbx
PACKAGE_VERSION =	0.65.0beta2

PACKAGE_SOURCE_NAME =	blackbox-${PACKAGE_VERSION}

PACKAGE_DESCRIPTION =	Blackbox Window Manager
PACKAGE_CATEGORY =	application

FAKE_DEST_VAR =

