#!/bin/sh
#
#  $Id: init_d_openssh,v 1.1.1.1 2001/11/09 18:24:33 zigg Exp $
#
#  Start/stop script for OpenSSH
#

case "$1" in
'start')
        ps -ef | awk '/usr.sbin.sshd/{print "kill",$2}' | sh
        if [ -f /usr/sbin/sshd ] ; then
                /usr/sbin/sshd
	else
		echo $0: could not find sshd >&2
		exit 1
        fi
        ;;
'stop')
        ps -ef | awk '/usr.sbin.sshd/{print "kill",$2}' | sh
        ;;
*)
        echo $0: usage: /etc/init.d/openssh { start | stop } >&2
        exit 1
        ;;
esac

