#!/bin/sh
#
#  $Id: postinstall,v 1.3 2002/07/08 17:24:35 zigg Exp $
#
#  Generate keys, setup privsep prerequisites, and start OpenSSH
#

if [ -f /etc/ssh_host_key ]
then
        echo 'rsa1 key already exists; skipping key generation' >&2
else
        /usr/bin/ssh-keygen -t rsa1 -f /etc/ssh_host_key -N ''
fi

if [ -f /etc/ssh_host_dsa_key ]
then
        echo 'dsa key already exists; skipping key generation' >&2
else
        /usr/bin/ssh-keygen -t dsa -f /etc/ssh_host_dsa_key -N ''
fi

if [ -f /etc/ssh_host_rsa_key ]
then
        echo 'rsa key already exists; skipping key generation' >&2
else
        /usr/bin/ssh-keygen -t rsa -f /etc/ssh_host_rsa_key -N ''
fi

if /usr/bin/id sshd
then
	echo 'sshd user already exists; not adding' >&2
else
	/usr/sbin/groupadd sshd
	/usr/sbin/useradd -d /var/empty -g sshd sshd
fi

/etc/init.d/openssh start

